package com.example.humiture.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.humiture.data.KuFangSetData;

import com.example.humiture.greenDao.KuFangSetDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig kuFangSetDataDaoConfig;

    private final KuFangSetDataDao kuFangSetDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        kuFangSetDataDaoConfig = daoConfigMap.get(KuFangSetDataDao.class).clone();
        kuFangSetDataDaoConfig.initIdentityScope(type);

        kuFangSetDataDao = new KuFangSetDataDao(kuFangSetDataDaoConfig, this);

        registerDao(KuFangSetData.class, kuFangSetDataDao);
    }
    
    public void clear() {
        kuFangSetDataDaoConfig.clearIdentityScope();
    }

    public KuFangSetDataDao getKuFangSetDataDao() {
        return kuFangSetDataDao;
    }

}
